Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -29,5 +29,5 @@ jobs:
       run: |
         mvn clean verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=meyy-innerpeace -Dsonar.projectKey=maven-sonar 
         STATUS=`curl -s https://sonarcloud.io/api/qualitygates/project_status?projectKey=maven-sonar | jq ".projectStatus.status"`
-        if [ "$STATUS" == "\"ERROR\"" ]; then    echo "MATCH"; else    echo "NOT"; fi
+        if [ "$STATUS" == "\"ERROR\"" ]; then    echo "Sonar Quality Gate Failed, Please check the Sonar log" && exit 1 ; fi
       # run: mvn clean install
